#!/usr/bin/env node
import { mkdir, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prompts from "prompts";
import kleur from "kleur";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = path.resolve(__dirname, "..", "templates");

type Provider =
  | "anthropic"
  | "openai"
  | "google"
  | "mistral"
  | "openrouter"
  | "ollama";

const PROVIDER_DEFAULTS: Record<Provider, { model: string; envKey: string; note?: string; baseUrl?: string }> = {
  anthropic:  { model: "claude-haiku-4-5",                   envKey: "ANTHROPIC_API_KEY" },
  openai:     { model: "gpt-4o-mini",                        envKey: "OPENAI_API_KEY" },
  google:     { model: "gemini-2.0-flash",                   envKey: "GOOGLE_GENERATIVE_AI_API_KEY" },
  mistral:    { model: "mistral-large-latest",               envKey: "MISTRAL_API_KEY" },
  openrouter: { model: "meta-llama/llama-3.3-70b-instruct",  envKey: "LLM_API_KEY",  note: "key from openrouter.ai/keys" },
  ollama:     { model: "qwen2.5:32b",                        envKey: "LLM_API_KEY",  baseUrl: "http://localhost:11434/v1", note: "no key needed — leave LLM_API_KEY empty" },
};

async function main() {
  console.log(kleur.cyan().bold("\n  Crucible Bench Agent Scaffolder\n"));

  const args = process.argv.slice(2);
  const dirArg = args[0];

  const questions: prompts.PromptObject[] = [];
  if (!dirArg) {
    questions.push({
      type: "text",
      name: "dir",
      message: "Project directory",
      initial: "my-crucible-agent",
      validate: (v: string) =>
        v && !v.includes("/") ? true : "Single dir name, no slashes",
    });
  }
  questions.push(
    {
      type: "text",
      name: "tokenId",
      message: "AgentINFT tokenId (from /my-agents)",
      initial: "1",
      validate: (v: string) => (/^\d+$/.test(v) ? true : "Numeric only"),
    },
    {
      type: "select",
      name: "language",
      message: "Language",
      choices: [
        { title: "TypeScript", value: "ts" },
        { title: "Python",     value: "py" },
      ],
    },
    {
      type: "select",
      name: "provider",
      message: "LLM provider (you can change this anytime in crucible.env)",
      choices: [
        { title: "Anthropic (Claude)",          value: "anthropic" },
        { title: "OpenAI (GPT)",                value: "openai" },
        { title: "Google (Gemini)",             value: "google" },
        { title: "Mistral",                     value: "mistral" },
        { title: "OpenRouter (~200 models)",    value: "openrouter" },
        { title: "Ollama (local)",              value: "ollama" },
      ],
    },
    {
      type: "text",
      name: "mcpUrl",
      message: "MCP server URL",
      initial: "http://localhost:8080/v1",
    }
  );

  const answers = await prompts(questions, {
    onCancel: () => {
      console.log(kleur.red("\n✗ Cancelled.\n"));
      process.exit(1);
    },
  });

  const targetDir = path.resolve(process.cwd(), dirArg ?? answers.dir);
  await mkdir(targetDir, { recursive: true });

  const lang = answers.language as "ts" | "py";
  const provider = answers.provider as Provider;
  const defaults = PROVIDER_DEFAULTS[provider];
  const templateLang = path.join(TEMPLATE_DIR, lang);

  const files =
    lang === "ts"
      ? ["package.json", "tsconfig.json", "agent.ts", "strategy.ts", "prompt.md", "README.md", ".gitignore"]
      : ["pyproject.toml", "agent.py", "strategy.py", "prompt.md", "README.md", ".gitignore"];

  for (const f of files) {
    try {
      await copyFile(path.join(templateLang, f), path.join(targetDir, f));
    } catch (e) {
      // .gitignore is optional; everything else must exist.
      if (f !== ".gitignore") throw e;
    }
  }

  const envText = `# Generated by create-crucible-agent on ${new Date().toISOString().slice(0, 10)}

# ─── 0G / Crucible Bench wiring ──────────────────────────────────────────────
AGENT_TOKEN_ID=${answers.tokenId}
AGENT_PRIVATE_KEY=0x__REPLACE_ME__   # download from /agents/${answers.tokenId} on cruciblebench.xyz
CRUCIBLE_MCP_URL=${answers.mcpUrl}
RUN_REGISTRY_V2=0x80C1496980BA1183f8368F6072a130D7B01eDA7D
SCENARIO=choppy-range

# ─── LLM provider ────────────────────────────────────────────────────────────
# Flip these three to swap providers; no code change needed.
# See README.md for examples of other providers.
LLM_PROVIDER=${provider}
LLM_MODEL=${defaults.model}
${defaults.baseUrl ? `LLM_BASE_URL=${defaults.baseUrl}\n` : ""}\
${provider === "anthropic" || provider === "openai" || provider === "google" || provider === "mistral"
  ? `${defaults.envKey}=`
  : `LLM_API_KEY=${defaults.note ? `  # ${defaults.note}` : ""}`}
`;
  await writeFile(path.join(targetDir, "crucible.env"), envText, "utf8");

  console.log(kleur.green(`\n✓ Created ${targetDir}\n`));
  console.log(kleur.dim("Next steps:"));
  console.log(`  cd ${path.relative(process.cwd(), targetDir) || "."}`);
  console.log(lang === "ts" ? `  pnpm install` : `  pip install -e .`);
  console.log(`  # Fill in AGENT_PRIVATE_KEY + your LLM key in crucible.env`);
  console.log(`  ${lang === "ts" ? "pnpm start" : "python agent.py"}\n`);
  console.log(kleur.dim(`Provider: ${provider} · Model: ${defaults.model}`));
  console.log(kleur.dim(`Edit prompt.md to change the system prompt without touching code.\n`));
}

main().catch((err) => {
  console.error(kleur.red("✗"), err);
  process.exit(1);
});
