#!/usr/bin/env node
import { mkdir, writeFile, copyFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";
import prompts from "prompts";
import kleur from "kleur";

const __dirname = path.dirname(fileURLToPath(import.meta.url));
const TEMPLATE_DIR = path.resolve(__dirname, "..", "templates");

async function main() {
  console.log(kleur.cyan().bold("\n  Crucible Bench Agent Scaffolder\n"));

  const args = process.argv.slice(2);
  const dirArg = args[0];

  const questions: prompts.PromptObject[] = [];
  if (!dirArg) {
    questions.push({
      type: "text",
      name: "dir",
      message: "Project directory",
      initial: "my-crucible-agent",
      validate: (v: string) =>
        v && !v.includes("/") ? true : "Single dir name, no slashes",
    });
  }
  questions.push(
    {
      type: "text",
      name: "tokenId",
      message: "AgentINFT tokenId (from /my-agents)",
      initial: "1",
      validate: (v: string) => (/^\d+$/.test(v) ? true : "Numeric only"),
    },
    {
      type: "select",
      name: "language",
      message: "Language",
      choices: [
        { title: "TypeScript", value: "ts" },
        { title: "Python", value: "py" },
      ],
    },
    {
      type: "text",
      name: "mcpUrl",
      message: "MCP server URL",
      initial: "http://localhost:8080/v1",
    }
  );

  const answers = await prompts(questions, {
    onCancel: () => {
      console.log(kleur.red("\n✗ Cancelled.\n"));
      process.exit(1);
    },
  });

  const targetDir = path.resolve(process.cwd(), dirArg ?? answers.dir);
  await mkdir(targetDir, { recursive: true });

  const lang = answers.language as "ts" | "py";
  const templateLang = path.join(TEMPLATE_DIR, lang);

  // Copy template files
  const files =
    lang === "ts"
      ? ["package.json", "tsconfig.json", "agent.ts", "README.md", ".gitignore"]
      : ["pyproject.toml", "agent.py", "README.md", ".gitignore"];

  for (const f of files) {
    await copyFile(path.join(templateLang, f), path.join(targetDir, f));
  }

  // Write crucible.env
  const envText = `# Generated by create-crucible-agent on ${new Date().toISOString().slice(0, 10)}
# Replace AGENT_PRIVATE_KEY with your hot key (download from /agents/${answers.tokenId} on cruciblebench.xyz)
AGENT_TOKEN_ID=${answers.tokenId}
AGENT_PRIVATE_KEY=0x__REPLACE_ME__
CRUCIBLE_MCP_URL=${answers.mcpUrl}
RUN_REGISTRY_V2=0x80C1496980BA1183f8368F6072a130D7B01eDA7D

# Add your LLM key:
ANTHROPIC_API_KEY=
SCENARIO=choppy-range
`;
  await writeFile(path.join(targetDir, "crucible.env"), envText, "utf8");

  console.log(kleur.green(`\n✓ Created ${targetDir}\n`));
  console.log(kleur.dim("Next steps:"));
  console.log(`  cd ${path.relative(process.cwd(), targetDir) || "."}`);
  console.log(lang === "ts" ? `  pnpm install` : `  pip install -e .`);
  console.log(`  # Fill in AGENT_PRIVATE_KEY + ANTHROPIC_API_KEY in crucible.env`);
  console.log(`  ${lang === "ts" ? "pnpm start" : "python agent.py"}\n`);
}

main().catch((err) => {
  console.error(kleur.red("✗"), err);
  process.exit(1);
});
